In [9]:
import tensorflow as tf
x_ = tf.placeholder(tf.float32, shape=[4,2], name="x-input")
y_ = tf.placeholder(tf.float32, shape=[4,1], name="y-input")

Theta1 = tf.Variable(tf.random_uniform([2,2], -1, 1), name="Theta1")
Theta2 = tf.Variable(tf.random_uniform([2,1], -1, 1), name="Theta2")

Bias1 = tf.Variable(tf.zeros([2]), name="Bias1")
Bias2 = tf.Variable(tf.zeros([1]), name="Bias2")

A2 = tf.sigmoid(tf.matmul(x_, Theta1) + Bias1)
Hypothesis = tf.sigmoid(tf.matmul(A2, Theta2) + Bias2)

cost = tf.reduce_mean(( (y_ * tf.log(Hypothesis)) + 
        ((1 - y_) * tf.log(1.0 - Hypothesis)) ) * -1)

train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

XOR_X = [[0,0],[0,1],[1,0],[1,1]]
XOR_Y = [[1],[0],[0],[1]]

init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)
for i in range(12001):
        res,_=sess.run([cost,train_step],feed_dict={x_:XOR_X,y_:XOR_Y})
        if i%1000==0:
            print ("iteration= ",i,"cost= ",res)
            print ("Validating output for XNOR GATE")
            result=sess.run(Hypothesis,feed_dict={x_:XOR_X})
            print (result)
#if i % 1000 == 0:
 #   print('Epoch ', i)
  #  print('Hypothesis ', sess.run(Hypothesis, feed_dict={x_: XOR_X, y_: XOR_Y}))
   # print('Theta1 ', sess.run(Theta1))
    #print('Bias1 ', sess.run(Bias1))
    #print('Theta2 ', sess.run(Theta2))
    #print('Bias2 ', sess.run(Bias2))
    #print('cost ', sess.run(cost, feed_dict={x_: XOR_X, y_: XOR_Y}))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
iteration=  0 cost=  0.702711
Validating output for XOR GATE
[[ 0.43724489]
 [ 0.4365685 ]
 [ 0.42650604]
 [ 0.42588732]]
iteration=  1000 cost=  0.693258
Validating output for XOR GATE
[[ 0.50311357]
 [ 0.50438493]
 [ 0.49186349]
 [ 0.49305576]]
iteration=  2000 cost=  0.693227
Validating output for XOR GATE
[[ 0.50439876]
 [ 0.50521731]
 [ 0.49399778]
 [ 0.49476647]]
iteration=  3000 cost=  0.693203
Validating output for XOR GATE
[[ 0.50425833]
 [ 0.50459534]
 [ 0.49468589]
 [ 0.49500313]]
iteration=  4000 cost=  0.693182
Validating output for XOR GATE
[[ 0.50409585]
 [ 0.50397098]
 [ 0.49530953]
 [ 0.49519345]]
iteration=  5000 cost=  0.693161
Validating output for XOR GATE
[[ 0.503941  ]
 [ 0.50337219]
 [ 0.49590418]
 [ 0.49537185]]
iteration=  6000 cost=  0.693143
Validating output for XOR GATE
[[ 0.50379252]
 [ 0.50279504]
 [ 0.4964745 ]
 [ 0.4955408 ]]
iteration=  7000 cost=  0.693124
Validating output for

In [10]:
  res,_=sess.run([cost,train_step])

InvalidArgumentError: You must feed a value for placeholder tensor 'y-input_8' with dtype float and shape [4,1]
	 [[Node: y-input_8 = Placeholder[dtype=DT_FLOAT, shape=[4,1], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'y-input_8', defined at:
  File "/Anaconda/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Anaconda/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-994d4dfe1d5e>", line 3, in <module>
    y_ = tf.placeholder(tf.float32, shape=[4,1], name="y-input")
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1530, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1954, in _placeholder
    name=name)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Anaconda/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'y-input_8' with dtype float and shape [4,1]
	 [[Node: y-input_8 = Placeholder[dtype=DT_FLOAT, shape=[4,1], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
