In [4]:
import tensorflow as tf
import numpy as np
x=tf.placeholder(tf.float32,shape=[None,2])
y=tf.placeholder(tf.float32,shape=[None,1])

weights=tf.Variable(tf.random_normal([2,1]),dtype=tf.float32)
bias=tf.Variable(tf.random_normal([1]),dtype=tf.float32)



multiply1=tf.add(tf.matmul(x,weights),bias)
z=tf.nn.sigmoid(multiply1)


cost=tf.reduce_mean((y*tf.log(z)+(1-y)*tf.log(1-z))*-1)
optimizer = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

inp=np.array([[0,0],[0,1],[1,0],[1,1]])


with tf.Session() as sess_and:
    op_and=np.array([[0],[0],[0],[1]])
    
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess_and.run([cost,optimizer],feed_dict={x:inp,y:op_and})
        
    print ("Validating output for AND GATE")
    result_and=sess_and.run(z,feed_dict={x:inp})
    print (result_and)


Validating output for AND GATE
[[ 0.00471882]
 [ 0.12759537]
 [ 0.12779485]
 [ 0.81883568]]


In [6]:
with tf.Session() as sess_not:
    op_not=np.array([[1],[0],[0],[0]])
    
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess_not.run([cost,optimizer],feed_dict={x:inp,y:op_not})
        
    print ("Validating output for NOT(X1) AND NOT(X2) GATE")
    result_not=sess_not.run(z,feed_dict={x:inp})
    print (result_not)


Validating output for AND GATE
[[ 0.805834  ]
 [ 0.07443137]
 [ 0.07594939]
 [ 0.00159006]]


In [9]:
print(result_not)

[[ 1.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [10]:
print(result_and)

[[ 0.00471882]
 [ 0.12759537]
 [ 0.12779485]
 [ 0.81883568]]


In [11]:
for i in range(4):
    if result_and[i] < 0.5:
        result_and[i] = 0
    else:
        result_and[i] = 1
        
print(result_and)

[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]


In [12]:
for i in range(4):
    if result_not[i] < 0.5:
        result_not[i] = 0
    else:
        result_not[i] = 1
        
print(result_not)

[[ 1.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [16]:
inp_new = np.concatenate([result_and,result_not],axis = 1)
print(inp_new)

[[ 0.  1.]
 [ 0.  0.]
 [ 0.  0.]
 [ 1.  0.]]


In [17]:
with tf.Session() as sess_or:
    op_or=np.array([[1],[0],[0],[1]])
    
    tf.global_variables_initializer().run()
    for i in range(12001):
        res,_=sess_or.run([cost,optimizer],feed_dict={x:inp_new,y:op_or})
        
    print ("Validating output for AND GATE")
    result_or=sess_or.run(z,feed_dict={x:inp_new})
    print (result_or)


Validating output for AND GATE
[[ 0.9401263 ]
 [ 0.07582489]
 [ 0.07582489]
 [ 0.93878108]]
